### ISSUE TITLE
【環境構築】サーバ側環境構築

### ISSUE THREAD

**Issue by KunieKAKIKI** [KunieKAKIKI/dive_into_share#1]
サーバ側の環境を構築する。

- [x] Railsにstaging環境を作成
- [x] githubにmaster、developブランチを設定（developをデフォルトに設定）
- [x] herokuで本番環境とstaging実行環境を作成
- [x] ステージング環境にBasic認証をかける

※term1ではテスト実装を行っていないため、現段階で自動デプロイ、自動マイグレーションは設定しない。

**Comment by norotime** [comment]
@KunieKAKIKI お！初級エンジニア講座に習ってのブランチですね？

**Comment by katanoZ** [comment]
@norotime 講座を参考にさせていただきました…！

**Comment by norotime** [comment]
@katanoZ いいですね！チェックボックスにしましょう。

**Comment by katanoZ** [comment]
サーバ側の環境を構築する。

- [ ] Railsにstaging環境を作成
- [ ] githubにmaster、developブランチを設定（developをデフォルトに設定）
- [ ] herokuで本番環境とstaging実行環境を作成
- [ ] ステージング環境にBasic認証をかける

※term1ではテスト実装を行っていないため、現段階で自動デプロイ、自動マイグレーションは設定しない。
