### ISSUE TITLE
【トップ】トップページ表示機能

### ISSUE THREAD

**Issue by KunieKAKIKI** [KunieKAKIKI/dive_into_share#10]
トップページの表示

下の2つが表示されている
- [ ] 思い（このアプリのコンセプト）
- [ ] 簡単な使い方の文章
- [ ] 使い方（ヘルプ）へのリンク（現時点では空リンク）

**Comment by norotime** [comment]
@KunieKAKIKI 完成イメージをここに記載、貼り付けていただけますか？
完成した、という状態がどのような状態なのかの認識合わせのため、箇条書きでも良いので完成要件を示しておくのが良いとお思います。

**Comment by KunieKAKIKI** [comment]
@norotime 完成要件を追記しました。

**Comment by norotime** [comment]
@KunieKAKIKI ええと、これはトップページを作成するイシューでしたっけ？それとも、トップページへのリンクを作成するものでしたっけ？混乱してきました。笑

**Comment by KunieKAKIKI** [comment]
@norotime トップページを作成するイシューです。

**Comment by KunieKAKIKI** [comment]
@norotime 

完成要件：下の2つが表示されている

- [ ] 思い（このアプリのコンセプト）
- [ ] 使い方（ヘルプ）へのリンク（現時点では空リンク）

**Comment by norotime** [comment]
@KunieKAKIKI そうそう。それです。
