### ISSUE TITLE
【環境構築】アプリ側環境構築

### ISSUE THREAD

**Issue by KunieKAKIKI** [KunieKAKIKI/dive_into_share#3]
アプリ全体の設定
- [x] 　日本語化、タイムゾーン設定
- [x] 　assetsの自動生成の抑制
- [x] 　readme記述

必要なGemの導入
- [x] 　テンプレートエンジンはslim
- [x] 　デバッグ用gem導入
- [x] 　Bootstrap4

**Comment by norotime** [comment]
@KunieKAKIKI いいですね〜。張り切っていきましょう。

**Comment by yousuke-shiraishi** [comment]
@norotime 
- [x] yarn をチーム全体に入れる
 - [x] bootstrap4 をチーム全体に入れる 
- [x] slim をチーム全体に入れる
- [x] assetsのスキップでとりあえずテストやペルパーファイルを入れない
- [x]  binding-pry をチーム全体に入れる
- [x]  jquery をチーム全体に入れる
 あたりを共通化する予定です。npmも必要。

**Comment by norotime** [comment]
@yousuke-shiraishi イシュー内のタスクをチェックボックスとして記載しておきましょう。

- [ ] チェック

- [ ] できますよ
