### ISSUE TITLE
【投稿】投稿表示機能

### ISSUE THREAD

**Issue by KunieKAKIKI** [KunieKAKIKI/dive_into_share#4]
投稿の詳細画面を表示
- [x]  postscontrollerのshow
- [ ] showで示されたテキストエリアの文章と選んだカテゴリとチーム名のモック
- [x] 投稿の編集、削除ボタン
- [x] コメント作成、削除
- [x] チームメーンバー表示の投稿者を太字に、権限保持者（現時点ではダミー）を別の色に

**Comment by norotime** [comment]
@KunieKAKIKI こちらも完成要件が気になります。どのような状態になったら完成なのか、レビュアーの方にも認識してもらう必要があるため、箇条書きで良いので記載して欲しいです。

**Comment by yousuke-shiraishi** [comment]
@norotime 
- [ ] postscontroller#ishowでviewを作る
- [ ] モデルをmigrationで作る。
- [ ] コメントテキスト文章とチーム名とカテゴリの選択された文章をモックで作ります。

**Comment by norotime** [comment]
@yousuke-shiraishi チェックボックスに〜〜〜！

**Comment by yousuke-shiraishi** [comment]
@norotime 

完成要件

投稿の詳細画面を表示
- [ ]  postscontrollerのshowページを作る
- [ ] showで示されたテキストエリアの文章と選んだカテゴリとチーム名のモック

**Comment by norotime** [comment]
@yousuke-shiraishi いいですね！その調子です。
