### ISSUE TITLE
【認証機能】ログイン機能

### ISSUE THREAD

**Issue by KunieKAKIKI** [KunieKAKIKI/dive_into_share#5]
ユーザーは会員登録後ログインすることができる

内容
- [x] deviseの導入（認証はデフォルトのメールアドレスとパスワード）
- [x] ルート設定確認
- [x] viewsファイルを準備
- [x] Userモデルを作成
- [x] メッセージの日本語化
- [x] ログイン画面作成

**Comment by norotime** [comment]
@KunieKAKIKI こちらも要件をもう少し細かく書いてくださいね。Gemを使うのかどうか、認証はどのように？名前も？など色々想定できます。

**Comment by KunieKAKIKI** [comment]
@norotime 

内容
- [ ] deviseの導入

**Comment by norotime** [comment]
@KunieKAKIKI コメントだけでなく、イシュー本体にも記載してくださいね。

**Comment by norotime** [comment]
コメントは流れちゃいますので。

**Comment by KunieKAKIKI** [comment]
@norotime イシュー内容も更新しました。
