### ISSUE TITLE
【データ作成】（term1）モデル作成

### ISSUE THREAD

**Issue by KunieKAKIKI** [KunieKAKIKI/dive_into_share#6]
term1で必要なモデルの作成
- [x] ユーザモデルとマイグレーションファイル作成
- [x] チームモデルとマイグレーションファイル作成
- [x] カテゴリモデルとマイグレーションファイル作成
- [x] 投稿モデルとマイグレーションファイル作成
- [x] コメントモデルとマイグレーションファイル作成
- [x] チームとユーザの中間テーブル
- [x] リレーションシップ設定
- [x] マイグレート（db/schema.rbの確認）
- [x] モデルとdb制約修正（ユーザモデル修正）
- [x] モデルとdb制約修正（teams_usersユニーク制約）
- [x] モデルとdb制約修正（categoriesユニーク制約）
- [x] モデルとdb制約修正（teams_usersユニーク制約）
- [x] テーブル名変更（teams_usersをmembershipsへ）
- [x] 生成された不要なファイルを削除

**Comment by norotime** [comment]
@KunieKAKIKI モデル作成とマイグレーションファイル作成は別ですか？

**Comment by katanoZ** [comment]
@norotime 
モデル作成、マイグレーションファイルの作成、マイグレート（schema.rb生成）までが1つのissueという想定です！（issue内容に箇条書きしました）

**Comment by norotime** [comment]
@katanoZ では、GitHubのチェックリスト表記を活用して記載しましょう！

- [ ] こんな感じ

- [ ] 追加することも

- [ ] チェックもできる！

**Comment by KunieKAKIKI** [comment]
@norotime 

内容
- [ ] ユーザモデルとマイグレーションファイル作成
- [ ] チームモデルとマイグレーションファイル作成
- [ ] カテゴリモデルとマイグレーションファイル作成
- [ ] 投稿モデルとマイグレーションファイル作成
- [ ] コメントモデルとマイグレーションファイル作成
- [ ] マイグレート（db/schema.rbの確認）
