### ISSUE TITLE
【データ作成】（term1）シードデータ作成

### ISSUE THREAD

**Issue by KunieKAKIKI** [KunieKAKIKI/dive_into_share#7]
term1で使用する、ユーザ、チーム、カテゴリ、投稿、コメントのシードデータを作成

（以下は最低限の要件、それ以上のデータを作成しても可とする）
- [x] チーム5件（画像は簡単なサンプルを使用）
- [x] 1番めのチームに所属するユーザ5人（画像は簡単なサンプルを使用）
- [x] 1番めのチームに所属するカテゴリ5件（画像は簡単なサンプルを使用）
- [x] 1番目のカテゴリに所属する投稿5件（画像は簡単なサンプルを使用）
- [x] 1番めの投稿に所属するコメント5件

**Comment by norotime** [comment]
@KunieKAKIKI シードデータはどのようなデータにしましょうか？完成要件を整理しておきましょう。

**Comment by katanoZ** [comment]
@norotime issue内容に記載しました！

**Comment by katanoZ** [comment]
term1で使用する、ユーザ、チーム、カテゴリ、投稿、コメントのシードデータを作成

（以下は最低限の要件、それ以上のデータを作成しても可とする）
- [ ] チーム5件（画像は簡単なサンプルを使用）
- [ ] 1番めのチームに所属するユーザ5人（画像は簡単なサンプルを使用）
- [ ] 1番めのチームに所属するカテゴリ5件（画像は簡単なサンプルを使用）
- [ ] 1番目のカテゴリに所属する投稿5件（画像は簡単なサンプルを使用）
- [ ] 1番めの投稿に所属するコメント5件
