### ISSUE TITLE
【サイドバー】共通サイドバー表示機能

### ISSUE THREAD

**Issue by KunieKAKIKI** [KunieKAKIKI/dive_into_share#8]
アプリ共通で使用するサイドバー部分を作成

- [x] アプリの全ての画面に共通でサイドバーが表示されている
- [x] サイドバー部分にチーム、カテゴリ、投稿の一覧が表示されている
- [x] チーム作成ボタンが表示されている

※投稿一覧のデザインや、アコーディオンメニュー 開閉などの画面効果は今回の要件には含めません。
　一覧の内容が表示がされている状態までを要件の範囲とします。

**Comment by norotime** [comment]
@KunieKAKIKI こちらも完成要件を！

**Comment by katanoZ** [comment]
アプリ共通で使用するサイドバー部分を作成

- [ ] アプリの全ての画面に共通でサイドバーが表示されている
- [ ] サイドバー部分にチーム、カテゴリ、投稿の一覧が表示されている

※投稿一覧のデザインや、アコーディオンメニュー 開閉などの画面効果は今回の要件には含めません。
　一覧の内容が表示がされている状態までを要件の範囲とします。

**Comment by yasuhisa1984** [comment]
@norotime レビューをお願いします。
