### ISSUE TITLE
【ヘッダ】共通ヘッダ表示機能

### ISSUE THREAD

**Issue by KunieKAKIKI** [KunieKAKIKI/dive_into_share#9]
@norotime アプリ共通で使用するヘッダを表示
- [x]  ロゴ　
- [x] 投稿リンク空リンク
- [x] マイページ空リンク
- [x] ログアウト空リンクを作る
- [x] お知らせ（数字とアイコン）※現時点ではデザインのみで機能しない
- [x] 共通フッター
- [ ] フラッシュメッセージの表示部分を作る

**Comment by norotime** [comment]
@KunieKAKIKI 完成要件を記載しましょう！

**Comment by yousuke-shiraishi** [comment]
@norotime bootstrap4でロゴ　投稿ボタン　チーム作成　マイページ　ログアウトの空リンクをナブバーに設定します。

**Comment by norotime** [comment]
@yousuke-shiraishi ですから、チェックボックスリストを使ってください・・・。笑
やり方は、柿木さんがご存知です。

**Comment by yousuke-shiraishi** [comment]
@norotime 

完成要件

アプリ共通で使用するヘッダを表示
- [x]  ロゴ　
- [x] 投稿リンク空リンク
- [x] マイページ空リンク
- [x] ログアウト空リンクを作る
- [x] お知らせについては文章からちゃんとしたアイコンにするまでモックの文章です。
